### PR TITLE
feature/compare

### PR DESCRIPTION
**Pull request by Manflack**
Well, something i dont understand, why when i change the interval value
500 to 3000 i got more files and folders in the injection of html?

I need understand that...

### CODE REVIEW

**Comment by richard-rance** [comment]
@Manflack I added some log output and it appears that the setInterval is only running once after page load. I found ```DOM-based timers, such as window.setTimeout() or window.setInterval(), are not honored in non-persistent background scripts if they trigger when the event page is dormant.``` at https://developer.chrome.com/extensions/background_migration#timers

500ms after page load github is not fully loaded so the `$('.file-info')` in buildTree only gets the files that have been rendered so far. 

We probably need to change the way that some of the functions get called.

**Comment by picheli20** [comment]
Agree with @lagerenas, maybe we can go for this alarm approach instead?

@Manflack would you be so kind and change update your MR? instead of the 3s timer

**Comment by Manflack** [comment]
@picheli20 Sure, I will see. Thanks guys!

**Comment by mrudelle** [comment]
A somewhat ugly fix for waiting for all files to load: #25 I have a 2000+ PR that takes a minute to load.

**Pull request closed without merging**
